name = "vista-reserve"
main = "src/index.js"
compatibility_date = "2026-06-30"

[assets]
directory = "public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "vista_reserve_db"
database_id = "fe8474e8-2d58-4841-827c-c4f8dbeb5e33"

[triggers]
# Hər bazar ertəsi saat 03:00 UTC (Azərbaycan vaxtı ilə səhər saat 07:00, UTC+4) işə düşür
crons = ["0 3 * * 2"]
